### ISSUE TITLE
Add "Load More" button below category-items

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#11]
To be applied to:
- author-profile page
- category page

Conditions:
- On page load, show 9 entries
- For each click of Load More button, append 9 more entries
- Order of entries should be latest on top, earlier at the bottom (normal feed order)

Please create class ".load-more" for Load More div so I can style. Thanks!

**Comment by RIanDeLaCruz** [comment]
http://code.tutsplus.com/tutorials/how-to-create-infinite-scroll-pagination--wp-24873

**Comment by janbelmonte** [comment]
@RIanDeLaCruz  daaaammmnnnn

**Comment by RIanDeLaCruz** [comment]
HAHAHA. kayang-kaya na @janbelmonte

**Comment by janbelmonte** [comment]
I leave it to your awesome powers

**Comment by RIanDeLaCruz** [comment]
I'll just be adding the class, but I've already uploaded the plugin

**Comment by RIanDeLaCruz** [comment]
just style it. Thanks @janbelmonte

**Comment by RIanDeLaCruz** [comment]
Hold that thought. It isn't loading the next set.

**Comment by RIanDeLaCruz** [comment]
Works properly now, @janbelmonte

**Comment by RIanDeLaCruz** [comment]
Styles na lang

**Comment by janbelmonte** [comment]
Anong class/id inassign mo for this?

**Comment by RIanDeLaCruz** [comment]
sabi mo gamitan ko ng .load-more, so I did.

it's just a link.
a#the-gdn-load-posts.loadmore

**Comment by janbelmonte** [comment]
Woops sorry! forgot about that

**Comment by janbelmonte** [comment]
@RIanDeLaCruz Saang file nakalagay to? As in the link itself

**Comment by RIanDeLaCruz** [comment]
It's in the plugin
