### ISSUE TITLE
Replace Twitter widget in author profile page with author description box

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#16]
Based on prototype

**Comment by RIanDeLaCruz** [comment]
Just posting the solution I had in mind here.

Create function to load blurbs. This is reusable.

if statements for home page, articles and author
load specific setup for each

**Comment by janbelmonte** [comment]
@RIanDeLaCruz Adding to that ^ I think you can make a condition na if wala pang description, put twitter widget na lang

**Comment by RIanDeLaCruz** [comment]
Noted
