### ISSUE TITLE
Add 2-3 more category items to fill remaining space underneath

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#17]
Applies to:
- category page
- author profile page

Also linking #11 here since it should be underneath the entries. (reminder lang)

**Comment by RIanDeLaCruz** [comment]
I can't have a different number of posts by default and what is to be added.

**Comment by janbelmonte** [comment]
Yeah, I meant add 2-3 more to your global default number of posts. Although teka, ilan na ba naka-set ngayon, 10?

**Comment by RIanDeLaCruz** [comment]
yeah, 10

**Comment by janbelmonte** [comment]
alright, thanks. ok na yan
