### ISSUE TITLE
Add/edit custom field in co-authors plugin for author course

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#18]
Options
1) Add a new field where we can input course of the author and reflect it on author page
2) Edit one of the existing fields so we can use it for author course

Check wp admin > users > guest authors and edit one of the authors to see existing fields

**Comment by RIanDeLaCruz** [comment]
https://wordpress.org/support/topic/guest-author-about-info-not-displayed

**Comment by RIanDeLaCruz** [comment]
@janbelmonte It seems that there is no way to do this and make the info appear outside the loop. What we could do is use a different field instead. Reappropriate the unused fields

**Comment by RIanDeLaCruz** [comment]
Let's just reappropriate. I don't think we can edit the boxes

**Comment by janbelmonte** [comment]
Alright, I have no problem with that. Listed it as option number 2 earlier ^^

**Comment by janbelmonte** [comment]
@RIanDeLaCruz So we won't necessarily rename the input field? We'll just treat one of the existing fields as a course field? Am I getting this right?

**Comment by RIanDeLaCruz** [comment]
I've hacked the plug in. Hahaha. We can now add the course

**Comment by janbelmonte** [comment]
Good job!

**Comment by RIanDeLaCruz** [comment]
Still am looking for a way to make it legit

**Comment by janbelmonte** [comment]
Also if you edited the plugin's source code, find a way to make sure your edits won't be removed once the plugin is updated.

**Comment by RIanDeLaCruz** [comment]
@janbelmonte I got it to work legit

**Comment by RIanDeLaCruz** [comment]
@janbelmonte I've already found a way to not break the the plug in. It can safely update now

**Comment by janbelmonte** [comment]
How did you do it?

On Wednesday, August 5, 2015, Ian De La Cruz <notifications@github.com>
wrote:

> @janbelmonte <https://github.com/janbelmonte> I've already found a way to
> not break the the plug in. It can safely update now
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theguidon/theguidon-twentyfifteen/issues/18#issuecomment-127897962>
> .
>


-- 
Sent from Mobile

Jan-Daniel S. Belmonte
Graphic Designer

(+63) 917 860 5870
www.janbelmonte.com

**Comment by RIanDeLaCruz** [comment]
I've created a function that saves the POST data from the fields.
