### ISSUE TITLE
Height of category item images should be consistent

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#21]
Check prototype

Applies to:
- category page
- author profile page

Willing to disregard if not doable

**Comment by RIanDeLaCruz** [comment]
It is consistent

![2015-08-04-230414_1318x744_scrot](https://cloud.githubusercontent.com/assets/7766185/9064039/30d3b9dc-3afd-11e5-870a-1489eaafd4b4.png)

**Comment by janbelmonte** [comment]
Oh, interesting. Although, check these screenshots from http://dev.theguidon.com/category/news/

![screenshot 2015-08-04 23 07 18](https://cloud.githubusercontent.com/assets/9819894/9064108/9d35591e-3afd-11e5-965e-a740dd6d3b6d.png)
![Uploading Screenshot 2015-08-04 23.07.12.png…]()

**Comment by RIanDeLaCruz** [comment]
please inspect each element @janbelmonte

**Comment by RIanDeLaCruz** [comment]
style issues kasi siya eh, not really development, unless inline styles

**Comment by janbelmonte** [comment]
@RIanDeLaCruz actually, yeah. Assigned this to you lang since I don't know how you propagated images? <img> lang ba siya or nakabackground...

**Comment by RIanDeLaCruz** [comment]
However you did it in your prototype, I followed to the letter @janbelmonte

**Comment by janbelmonte** [comment]
@RIanDeLaCruz  Ah okay gets ko na how to fix this. Sorry!

**Comment by RIanDeLaCruz** [comment]
Ok ok. I'll just read the prototype log when you fix it.  @janbelmonte

**Comment by janbelmonte** [comment]
Note: Create div for category-item image, set overflow hidden

**Comment by RIanDeLaCruz** [comment]
Just close this once you fixed it in the prototype.

**Comment by RIanDeLaCruz** [comment]
I'll do it now

**Comment by janbelmonte** [comment]
@RIanDeLaCruz got it

**Comment by janbelmonte** [comment]
Wait, you'll do what

**Comment by RIanDeLaCruz** [comment]
Nevermind. Ikaw na bahala.

**Comment by janbelmonte** [comment]
HAHA okay it's my fault so i'll fix it <3

**Comment by janbelmonte** [comment]
I'll disregard this for the meantime.
