### ISSUE TITLE
Make nameplate + menu sticky

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#22]
Nameplate and menu should stick to top of viewport while scrolling

@RIanDeLaCruz sorry, i don't have time to do the JS for this so if you could please do it na lang, thanks!

**Comment by RIanDeLaCruz** [comment]
ok

**Comment by RIanDeLaCruz** [comment]
This can be implemented in CSS.

Try this:

nameplate, menu {position:fixed}
menu has no more margintop in the toggled and untoggled state
Add a margin to the top of the content divs equal to the height of the nameplate

**Comment by RIanDeLaCruz** [comment]
If you want the content to also push down when opening the menu, I'll just add a javascript function for that.

**Comment by janbelmonte** [comment]
OO NGA PALA
<---- BOBO

Reassigning to myself for fixing
