### ISSUE TITLE
Fix spaces below nameplate

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#24]
1. There should be no extra space in between nameplate and category name
![screenshot 2015-08-06 14 39 52](https://cloud.githubusercontent.com/assets/9819894/9105353/63c6c7a6-3c49-11e5-9b17-9d40c3c70f12.png)

![screenshot 2015-08-06 14 44 05](https://cloud.githubusercontent.com/assets/9819894/9105376/a4f25420-3c49-11e5-8486-bcf4881a4f9a.png)

2. Space here is too big
![screenshot 2015-08-06 14 42 54](https://cloud.githubusercontent.com/assets/9819894/9105363/77aed128-3c49-11e5-925f-3b743cbaf61e.png)

**Comment by RIanDeLaCruz** [comment]
wala siya sa akin spaces.

![2015-08-06-183504_1366x768_scrot](https://cloud.githubusercontent.com/assets/7766185/9109669/f109fb36-3c69-11e5-86a1-4eeb6f2dce4e.png)

**Comment by janbelmonte** [comment]
@RIanDeLaCruz Chrome?

**Comment by janbelmonte** [comment]
Ahh yung wp admin navbar pala nagpupush sa kanya pababa.
