### ISSUE TITLE
Search input field should take full-width and full-height of parent div

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#25]
![screenshot 2015-08-06 14 49 36](https://cloud.githubusercontent.com/assets/9819894/9105443/713044de-3c4a-11e5-8516-8aec0ba36eac.png)

**Comment by RIanDeLaCruz** [comment]
@janbelmonte could you just create a class for this?

**Comment by janbelmonte** [comment]
@RIanDeLaCruz #search is assigned to that, idk why the style's not working

**Comment by RIanDeLaCruz** [comment]
Oh, that's because search is the wrapper. 
It's structure is:
form#search
--label
----input
--button

**Comment by janbelmonte** [comment]
Thanks!
