### ISSUE TITLE
Author image does not reflect on author page

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#27]
![screenshot 2015-08-06 18 33 54](https://cloud.githubusercontent.com/assets/9819894/9109635/c7f25702-3c69-11e5-832d-3f806b96570b.png)

![screenshot 2015-08-06 18 33 57](https://cloud.githubusercontent.com/assets/9819894/9109641/cd81411a-3c69-11e5-80b7-ff51d28ddf1e.png)

**Comment by RIanDeLaCruz** [comment]
I've commented out the loading of the image.

**Comment by RIanDeLaCruz** [comment]
Will add the conditional and figure out the appropriate size but it's working already

**Comment by RIanDeLaCruz** [comment]
Conditional is now working
