### ISSUE TITLE
Some pages have wrong category tags even if correct categories are ticked in admin

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#28]
For article, The Return of "Blue Eagle, The King"

![screenshot 2015-08-06 18 59 28](https://cloud.githubusercontent.com/assets/9819894/9110102/78948cda-3c6d-11e5-8c67-69f7155f8ff9.png)

![screenshot 2015-08-06 18 59 45](https://cloud.githubusercontent.com/assets/9819894/9110119/8fc52004-3c6d-11e5-8313-d490c8020a1c.png)

**Comment by RIanDeLaCruz** [comment]
Done

**Comment by janbelmonte** [comment]
Should be Opinion > Chalkmarks
![screenshot 2015-08-07 17 22 43](https://cloud.githubusercontent.com/assets/9819894/9132831/05490654-3d29-11e5-876f-be5cbe4b65af.png)

**Comment by RIanDeLaCruz** [comment]
fixed again.
![2015-08-07-193812_1366x768_scrot](https://cloud.githubusercontent.com/assets/7766185/9134994/de5ea93c-3d3b-11e5-99c8-aec18d319b2f.png)
