### ISSUE TITLE
Please list down all of the files concerning comments section here

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#30]

**Comment by RIanDeLaCruz** [comment]
comments.php and functions.php

**Comment by janbelmonte** [comment]
How about copy? Where can I change the copy? Like the labels and stuff. (text, not style)

**Comment by RIanDeLaCruz** [comment]
It's in functions @janbelmonte

**Comment by janbelmonte** [comment]
Got it thanks, will close this after I'm done resolving.

**Comment by janbelmonte** [comment]
@RIanDeLaCruz  Where can I edit:
"You may use these HTML tags and attributes: <a href="" title=""> <abbr title=""> <acronym title=""> <b> <blockquote cite=""> <cite> <code> <del datetime=""> <em> <i> <q cite=""> <s> <strike> <strong>"

**Comment by RIanDeLaCruz** [comment]
use this 
'comment_notes_after' => '<p class="form-allowed-tags">' .
    sprintf(
      __( 'You may use these <abbr title="HyperText Markup Language">HTML</abbr> tags and attributes: %s' ),

just add it to $comment_args variable in comment.php

**Comment by RIanDeLaCruz** [comment]
Please see http://codex.wordpress.org/Function_Reference/comment_form

**Comment by janbelmonte** [comment]
Lol, I'm breaking it. Sorry, really not versed with wp development. Can you just please remove that part. We don't need to show it.

**Comment by RIanDeLaCruz** [comment]
Ok. HAHA

**Comment by RIanDeLaCruz** [comment]
Done

**Comment by RIanDeLaCruz** [comment]
wait. Something broke

**Comment by RIanDeLaCruz** [comment]
Misplaced semi-colon

**Comment by janbelmonte** [comment]
@RIanDeLaCruz How's this doing?

**Comment by RIanDeLaCruz** [comment]
done

**Comment by RIanDeLaCruz** [comment]
Wait. Something must've happened to the file. Wait

**Comment by janbelmonte** [comment]
omg nagsave ako sa functions.php, baka na-overwrite ko yung sayo haha

**Comment by RIanDeLaCruz** [comment]
what did you do sa functions

**Comment by RIanDeLaCruz** [comment]
Nah. It didn't. I wasn't able to upload lang

**Comment by janbelmonte** [comment]
Ah okay, pero you're working on top of my previously edited functions right? I just moved stuff around, changed a class.

**Comment by RIanDeLaCruz** [comment]
Don't need to fix anything inside functions

**Comment by janbelmonte** [comment]
@RIanDeLaCruz Where/how to edit this area? Or ikaw na lang ulit?

![screenshot 2015-08-08 12 29 07](https://cloud.githubusercontent.com/assets/9819894/9149074/2874ba10-3dc9-11e5-91bc-8417da36bf4f.png)

**Comment by janbelmonte** [comment]
nvm found it

**Comment by janbelmonte** [comment]
@RIanDeLaCruz gaaah, bumalik yung you may use html tags shit

**Comment by RIanDeLaCruz** [comment]
Yeah.

**Comment by RIanDeLaCruz** [comment]
wala na ulit @janbelmonte. I think out comments.php are overriding each other

**Comment by janbelmonte** [comment]
Onga eh. Sorry about that. Thanks!
