### ISSUE TITLE
Move comments section from bottom of page (mobile)

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#31]
Right now, the comments area appears at the very bottom. We need to move it below the content area and above the sidebar. Can this be done?

**Comment by RIanDeLaCruz** [comment]
Yep. It could be done.

**Comment by RIanDeLaCruz** [comment]
@janbelmonte This works, but only real mobile devices only.

**Comment by janbelmonte** [comment]
Working now. Thanks!
