### ISSUE TITLE
Search results: Show same number of items as category page and add Load More Posts button

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#32]
Is it all of the results at once, or have you also placed the Load More button?

**Comment by RIanDeLaCruz** [comment]
I do not understand the question

**Comment by RIanDeLaCruz** [comment]
It's programmed to get everything

**Comment by janbelmonte** [comment]
So if I search: "charot"
and there are 200 search results for charot
pages loads and shows me 200 items immediately?

**Comment by RIanDeLaCruz** [comment]
Yep. I could fix that.

**Comment by janbelmonte** [comment]
Alright, please make it behave the same way as the category page :D

**Comment by RIanDeLaCruz** [comment]
Ok.

**Comment by RIanDeLaCruz** [comment]
Ok. Done.
