### ISSUE TITLE
Change message for 0 search results

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#33]
![screenshot 2015-08-08 13 59 03](https://cloud.githubusercontent.com/assets/9819894/9149296/1a3778ea-3dd6-11e5-82b6-3b2f18a7423d.png)

If there are no results for a given search term,
retain "Search results for: [search term]" from original search results page
below it, display "Sorry, we cannot find anything with those keywords." instead of "No more posts to load."

**Comment by janbelmonte** [comment]
Also, please remove 404 text.

**Comment by RIanDeLaCruz** [comment]
I actually like the 404 text =))

**Comment by RIanDeLaCruz** [comment]
But I realized search page pala to

**Comment by janbelmonte** [comment]
HAHA I like it also, I hope the EB won't decide against it =))

**Comment by RIanDeLaCruz** [comment]
Benta eh. I think they'll like it

**Comment by RIanDeLaCruz** [comment]
Should be working now.

**Comment by janbelmonte** [comment]
Still lacking:
- "Search results for: [search term]" from original search results page
- remove 404 message

**Comment by janbelmonte** [comment]
change "cannot" to "can't" na lang pala, sorry copywriting shit haha thanks

**Comment by RIanDeLaCruz** [comment]
Ok. hindi ko lang pala na-upload =))

**Comment by RIanDeLaCruz** [comment]
uploaded

**Comment by janbelmonte** [comment]
Same pa rin. Can't lang yung nagbago

**Comment by RIanDeLaCruz** [comment]
should be fine now

**Comment by RIanDeLaCruz** [comment]
forgot to upload search template

**Comment by janbelmonte** [comment]
Thanks!
