### ISSUE TITLE
Please remove search bar autofocus, breaks nameplate on mobile

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#36]
Please try also on Android. The goal is to stop it from zooming/focusing when user taps.
Sometimes, when it really zooms in, the GUIDON logo drops one line because of lack of space.

Note: Don't mind the search icon first, I'll fix that once this is fixed.

![img_1103](https://cloud.githubusercontent.com/assets/9819894/9149428/f447c968-3ddb-11e5-9737-ab80a68cb824.PNG)

**Comment by RIanDeLaCruz** [comment]
I think that we just have to fix the style setting of #search:focus. People have an expectation that when they click search, the cursor is already there.

As for zoom, I'll fix it na.

**Comment by janbelmonte** [comment]
@RIanDeLaCruz Ah, I'm okay with the cursor. Yung zoom lang ayoko.

**Comment by RIanDeLaCruz** [comment]
Ahhh, sabi mo kasi remove autofocus eh

**Comment by janbelmonte** [comment]
Sorry di ko lang alam proper term haha

**Comment by RIanDeLaCruz** [comment]
Uhm, I've tried a fix. I'll upload to dev

**Comment by RIanDeLaCruz** [comment]
It's not zooming already

**Comment by RIanDeLaCruz** [comment]
I'm thinking of using the calc() function to fix the search bar but it doesn't seem to work. Though all the browsers should be supporting it already

**Comment by janbelmonte** [comment]
Alright, no more zoom. Thanks! I'll fix the search bar na lang :)
