### ISSUE TITLE
Fix search label style on mobile to give space for search icon

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#37]

**Comment by RIanDeLaCruz** [comment]
I've found a solution! @janbelmonte

**Comment by janbelmonte** [comment]
@RIanDeLaCruz feel free to upload, i'll wait to checl

**Comment by RIanDeLaCruz** [comment]
use this:

#search label {
  width: calc(100% - 80px);
  width: -webkit-calc(100% - 80px);
  width: -moz-calc(100% - 80px);
  width: -o-calc(100% - 80px);
  width: -ms-calc(100% - 80px);
  width: 80%; /* This is just a fallback */
}

#search input {
  width:inherit;
}

**Comment by RIanDeLaCruz** [comment]
Sige. I'll do it na

**Comment by janbelmonte** [comment]
Bakit 80px? San mo naderive yun

**Comment by RIanDeLaCruz** [comment]
DevTools

**Comment by RIanDeLaCruz** [comment]
actually, hula lang. But It should be smaller

**Comment by RIanDeLaCruz** [comment]
The value should be equal to the total width of the icon

**Comment by janbelmonte** [comment]
HAHAHA Ah, okay. Well my plan was to just make the label width: 75% for mobile but that does the job more accurately. :)

**Comment by janbelmonte** [comment]
Gets gets

**Comment by RIanDeLaCruz** [comment]
Kaya nga. But lagyan na lang natin ng fallback na 75%

**Comment by RIanDeLaCruz** [comment]
It should be working now. Tell me before I commit

**Comment by janbelmonte** [comment]
Aryt. Tell me pag uploaded na. Luv luv

**Comment by janbelmonte** [comment]
Sobrang di maganda for my legacy na makikita ng future GUIDONeers yung false kabaklaan ko sa GitHub

**Comment by janbelmonte** [comment]
charot chorva!!!

**Comment by RIanDeLaCruz** [comment]
HAHAHAHAHAHA

**Comment by RIanDeLaCruz** [comment]
Teka lang. Nag-override ang stuff

**Comment by RIanDeLaCruz** [comment]
Did you see it already @janbelmonte
