### ISSUE TITLE
Article Title Issue

### ISSUE THREAD

**Issue by RIanDeLaCruz** [theguidon/theguidon-twentyfifteen#4]
Article title is skewing a lot of things.The text is not responsive.

![image](https://cloud.githubusercontent.com/assets/7766185/8542175/48e253b4-24c6-11e5-9b99-54be061318d1.png)

![image](https://cloud.githubusercontent.com/assets/7766185/8542234/bfd2292c-24c6-11e5-8637-285481a64f83.png)

**Comment by theguidon** [comment]
Noted. Will work on this during my styling stage after all pages are constructed. Thanks, @RIanDeLaCruz
