### ISSUE TITLE
Create container div for blurb images to limit height

### ISSUE THREAD

**Issue by RIanDeLaCruz** [theguidon/theguidon-twentyfifteen#41]
![2015-08-09-221113_1318x744_scrot](https://cloud.githubusercontent.com/assets/7766185/9155229/9e92954e-3ee3-11e5-983b-1d9eadc32f88.png)

**Comment by janbelmonte** [comment]
Can you do this for me na lang? I can't edit the blurb.php cause I might mess it up. Please add a div that will contain the blurb image

- div height should be 190px
- image width = 100%
- overflow: hidden;
- center the image vertically and horizontally inside the div

**Comment by janbelmonte** [comment]
@RIanDeLaCruz ^

**Comment by RIanDeLaCruz** [comment]
Noted

**Comment by RIanDeLaCruz** [comment]
Already fixed it. Referenced Issue #57 in the commit
