### ISSUE TITLE
Thumbnails are loading full size; fix image rendition sizes to decrease bandwidth

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#42]

**Comment by RIanDeLaCruz** [comment]
@janbelmonte just figure out the best size per image. I'm always using full size in the code

**Comment by RIanDeLaCruz** [comment]
I'll edit it in the code

**Comment by janbelmonte** [comment]
Yup, will still figure out ideal dimensions for:
- thumbnail (blurb images)
- medium (article content)
- large (fullscreen article layout)

Made an issue for this since I noticed that the category pages are loading slowly. The thumbnails are loading images bigger than 2000px pala, haha!

**Comment by janbelmonte** [comment]
Changed sizes to:
- Thumbnail: 400 px
- Medium: 800 px
- Large: 1400 px

Will rerender all images later, just have to back files up.

**Comment by janbelmonte** [comment]
@RIanDeLaCruz You can change assigned images now.

Thumbnails - thumbnail size
NSO story banner image - medium
Pullout (full screen) banner image - large

Close this once you're done. Thanks.
