### ISSUE TITLE
Add "By" and publish date to bylines in category and search results templates

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#43]
1. Add "By" before names
2. Add publish date after names

![screenshot 2015-08-09 22 18 47](https://cloud.githubusercontent.com/assets/9819894/9155250/ba033328-3ee4-11e5-8482-35382690bb1d.png)

**Comment by RIanDeLaCruz** [comment]
format please @janbelmonte

**Comment by janbelmonte** [comment]
Oops, duplicate pala yung isa. Please see #52
