### ISSUE TITLE
Load 15 items on first load of category/search results pages

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#44]
Reason: Number of items on first load should be of equal height with sidebar. Right now, the white space below the first ten items makes it look like the sidebar forced the page down, thus leaving white space. More power to the items (lol)

**Comment by RIanDeLaCruz** [comment]
This would load 15 on click ha

**Comment by janbelmonte** [comment]
Yes please, @RIanDeLaCruz ty ty

**Comment by RIanDeLaCruz** [comment]
It's been implemented already. I'll just push in a few.
