### ISSUE TITLE
Fix width of Twitter embed

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#46]
@RIanDeLaCruz I'll try to see if I can tweak the regular Twitter embed but if you have time, kindly see if we can get a plugin that will allow us to use our own CSS and make it look more united with the rest of the website. Just post links to recommendations here. Thanks!

**Comment by RIanDeLaCruz** [comment]
We can edit naman. Kindly see twitter-widget partial

**Comment by RIanDeLaCruz** [comment]
Ok. Nevemind previous comment. I'll look around

**Comment by RIanDeLaCruz** [comment]
https://github.com/twitter/wordpress

It's the official Twitter Plugin
