### ISSUE TITLE
Change head format

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#47]
![screenshot 2015-08-09 22 42 41](https://cloud.githubusercontent.com/assets/9819894/9155354/03c67a62-3ee8-11e5-89d8-f4b1a8c5d53f.png)

**Comment by RIanDeLaCruz** [comment]
What will be the head format

**Comment by janbelmonte** [comment]
Home — The GUIDON
Beyond Loyola — The GUIDON
etc etc

**Comment by RIanDeLaCruz** [comment]
Ok. Thanks @janbelmonte
