### ISSUE TITLE
Add new section descriptions from editors

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#48]

**Comment by tekamoment** [comment]
Final descriptions:

**News**
News chronicles the pressing issues and events that involve the Ateneo. The section aims to record stories as they happen, and inform the Ateneo community through accurate and timely articles.

**Sports**
The GUIDON Sports highlights the Ateneo athletes who have devoted themselves to  their disciplines to represent the Blue and White. The section undertakes the same amount of dedication while chronicling the world of Ateneo sports.

**Opinion**
The GUIDON's Opinion section features articles expressing the opinions of the publication, members of The GUIDON Editorial Board, and students and faculty members of the Loyola Schools.

**Features**
Features covers the stories of culture as they occur, as Ateneans experience them. Be it with the latest food movements or on larger media trends, the section strives to regularly be in-the-know as it engages these diverse currents.

**Vantage**
Vantage is the online magazine of The GUIDON. It is tasked with exploring and engaging the rich culture of the Ateneo community by using different forms of media to capture the sights, the sounds, and the spirit of the Atenean.

They are okay with the current descriptors for BL and Inquiry.

**Comment by janbelmonte** [comment]
Awesome. Thanks!

**Comment by tekamoment** [comment]
:+1:
