### ISSUE TITLE
Blurb Images Sizing

### ISSUE THREAD

**Issue by RIanDeLaCruz** [theguidon/theguidon-twentyfifteen#5]
The images on the blurbs have no defined height and it inherits a wrong height setting 
![image](https://cloud.githubusercontent.com/assets/7766185/8894130/09be5c9c-33de-11e5-866e-63f22b772a00.jpg)

**Comment by RIanDeLaCruz** [comment]
![image](https://cloud.githubusercontent.com/assets/7766185/8894116/bb783666-33dd-11e5-874f-ff149f49fa4b.jpg)

**Comment by janbelmonte** [comment]
Whaaaat, hahaha. I've never encountered this. How can I replicate the issue?

**Comment by RIanDeLaCruz** [comment]
Try and install the theme.

**Comment by janbelmonte** [comment]
@RIanDeLaCruz Okay, I'll install it on dev.theguidon

**Comment by RIanDeLaCruz** [comment]
@janbelmonte Don't you have a local?:))) but okay

**Comment by RIanDeLaCruz** [comment]
BTW, this issue is due to the size used by WordPress itself. In line yung issue eh

**Comment by janbelmonte** [comment]
@RIanDeLaCruz Size of what?

**Comment by RIanDeLaCruz** [comment]
@janbelmonte The thumbnail as defined by WordPress

**Comment by janbelmonte** [comment]
@RIanDeLaCruz Ah so may inline style yung thumbnail dictated by WordPress?

**Comment by RIanDeLaCruz** [comment]
@janbelmonte  yep.

**Comment by janbelmonte** [comment]
@RIanDeLaCruz I think this has been resolved na? Closing for now. Reopen if necessary. Thanks.
