### ISSUE TITLE
Comments area styling

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#50]
Check this article: http://dev.theguidon.com/2015/05/ateneo-hosts-14th-afc-monfort-football-festival/

There's a huge space between the end of the content and the comments area.

![screenshot 2015-08-09 22 45 57](https://cloud.githubusercontent.com/assets/9819894/9155375/77540350-3ee8-11e5-92c9-c6715ceaa427.png)

**Comment by RIanDeLaCruz** [comment]
Note to self: col-sm-9 div is to be moved from the partials to single.php to allow modification of where it is on the page

**Comment by RIanDeLaCruz** [comment]
@janbelmonte please do just fix the style of this. I've changed it in the dev site.

**Comment by janbelmonte** [comment]
Will do once I get home.

On Mon, Aug 10, 2015 at 1:19 PM, Ian De La Cruz <notifications@github.com>
wrote:

> @janbelmonte <https://github.com/janbelmonte> please do just fix the
> style of this. I've changed it in the dev site.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theguidon/theguidon-twentyfifteen/issues/50#issuecomment-129304152>
> .
>



-- 
*Jan-Daniel S. Belmonte*
Graphic Designer
Quality Assurance Analyst, Rappler

(+63) 917 860 5870
www.janbelmonte.com
