### ISSUE TITLE
Add publish date to article pages (below byline)

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#52]

**Comment by RIanDeLaCruz** [comment]
format please

**Comment by janbelmonte** [comment]
@RIanDeLaCruz 
Month Day, Year
May 11, 2015

Example combined with byline:
By Joff D. Bantayan<br>
Published 4:25 PM, May 11, 2015

**Comment by janbelmonte** [comment]
Update:
Let's make it consistent with our comments box.

Example:
By Your Mom
Published March 13, 2015 at 2:49 PM"
