### ISSUE TITLE
Change "Chalkmarks" to "Chalk Marks"

### ISSUE THREAD

**Issue by tekamoment** [theguidon/theguidon-twentyfifteen#54]
The professor-written columns in the newspaper are listed as "Chalk Marks", not as "Chalkmarks". 

<img width="264" alt="screen shot 2015-08-09 at 11 29 36 pm" src="https://cloud.githubusercontent.com/assets/765270/9155562/8525ba86-3eee-11e5-8d0e-62e0943b0ed9.png">
<img width="413" alt="screen shot 2015-08-09 at 11 29 30 pm" src="https://cloud.githubusercontent.com/assets/765270/9155563/8554c7cc-3eee-11e5-8859-3dbb25b436af.png">

**Comment by janbelmonte** [comment]
Is it really? Omg, I don't remember. Well, this'll just be edited in the WP categories. Reassigning to me.

**Comment by tekamoment** [comment]
@janbelmonte Noted!
