### ISSUE TITLE
Remove huge space below comment area

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#58]
![screenshot 2015-08-09 23 34 41](https://cloud.githubusercontent.com/assets/9819894/9155601/4e0152bc-3eef-11e5-9bfb-08ac7933e715.png)

**Comment by tekamoment** [comment]
Interesting thing about this bug: the white space *scales* with the browser width! Bigger browser width = bigger space. The space is eliminated once we get closer to mobile width.

Compare these two images:
<img width="1257" alt="screen shot 2015-08-09 at 11 51 00 pm" src="https://cloud.githubusercontent.com/assets/765270/9155655/86670172-3ef1-11e5-8272-52bafce42cd4.png">
and
<img width="1792" alt="screen shot 2015-08-09 at 11 51 04 pm" src="https://cloud.githubusercontent.com/assets/765270/9155660/8e228fa8-3ef1-11e5-8e3e-311bab39aafc.png">

**Comment by janbelmonte** [comment]
I'm guessing, the content area gets squished and the text gets pushed down? Is the div of the comment area below both the content and sidebar areas, @RIanDeLaCruz ? Probably related to #50

**Comment by RIanDeLaCruz** [comment]
I've fixed this already. If you aren't happy with it, just re-open this. Thanks. @janbelmonte @tekamoment
