### ISSUE TITLE
Some fonts aren't working

### ISSUE THREAD

**Issue by theguidon** [theguidon/theguidon-twentyfifteen#6]
- Content area text should be Mercury Roman (check @font-face)
- Caption text should be Univers

**Comment by RIanDeLaCruz** [comment]
@janbelmonte there is no font setting for caption-featured id

**Comment by RIanDeLaCruz** [comment]
@janbelmonte the body copy is in Mercy Text Roman

**Comment by janbelmonte** [comment]
@riandelacruz okay, will set font for caption-featured

meanwhile here's what i get for the body copy
![screenshot 2015-08-04 22 00 47](https://cloud.githubusercontent.com/assets/9819894/9062337/682cb662-3af4-11e5-9a3d-3bd205a152ee.png)
