### ISSUE TITLE
The GUIDON logo displaces at mobile browser widths

### ISSUE THREAD

**Issue by tekamoment** [theguidon/theguidon-twentyfifteen#60]
Included are samples from Chrome and Firefox (both on Mac).

<img width="512" alt="screen shot 2015-08-09 at 11 38 25 pm" src="https://cloud.githubusercontent.com/assets/765270/9155622/e3ef0814-3eef-11e5-9d3a-cd2e10bb60d7.png">
<img width="447" alt="screen shot 2015-08-09 at 11 38 22 pm" src="https://cloud.githubusercontent.com/assets/765270/9155621/e3ed7760-3eef-11e5-840a-c76d7c41a666.png">

(Can't actually get samples from my phone right now because of IP blacklisting, haha.)

**Comment by janbelmonte** [comment]
@tekamoment our media queries take device width so if you simulate it by decreasing browser size, it won't /super/ work. Nevertheless, I'll try to solve this pa rin. Try to check on actual mobile devices :) TY!
