### ISSUE TITLE
Search bar expands too much at smaller browser widths

### ISSUE THREAD

**Issue by tekamoment** [theguidon/theguidon-twentyfifteen#61]
For both regular desktop:
<img width="1250" alt="screen shot 2015-08-09 at 11 47 48 pm" src="https://cloud.githubusercontent.com/assets/765270/9155653/1e8271e0-3ef1-11e5-8e47-782f757b9e72.png">
and mobile:
<img width="389" alt="screen shot 2015-08-09 at 11 46 06 pm" src="https://cloud.githubusercontent.com/assets/765270/9155651/ec2c8e42-3ef0-11e5-8d40-bba3063d7c64.png">

Picture included shows Chrome (Mac). Reproducible on Firefox.

**Comment by janbelmonte** [comment]
@RIanDeLaCruz oh my, #37 is back. DUN DUNNN

**Comment by RIanDeLaCruz** [comment]
Nawala yung calc function

**Comment by RIanDeLaCruz** [comment]
Kasama pala ito dun sa moments na na override yung gawa ko at gawa mo
