### ISSUE TITLE
Benny's byline search comes up with no results

### ISSUE THREAD

**Issue by tekamoment** [theguidon/theguidon-twentyfifteen#62]
Issue with the ñ?

<img width="1792" alt="screen shot 2015-08-09 at 11 54 37 pm" src="https://cloud.githubusercontent.com/assets/765270/9155682/00c05766-3ef2-11e5-998b-00db80c8280e.png">

**Comment by janbelmonte** [comment]
ooohhh shiiiiiittt

**Comment by janbelmonte** [comment]
Weird. His name is spelled correctly sa Guest Authors. There are 19 articles attributed to him.

![screenshot 2015-08-09 23 57 02](https://cloud.githubusercontent.com/assets/9819894/9155697/669b39f2-3ef2-11e5-93fa-a4fd4445a87e.png)

**Comment by tekamoment** [comment]
Hmm. I guess the issue is caused by having his ñ change to an n? That's how it appears in the URL.

**Comment by janbelmonte** [comment]
Merp, that's also the slug registered on the system so there shouldn't be a mismatch.

![screenshot 2015-08-10 00 00 13](https://cloud.githubusercontent.com/assets/9819894/9155704/dea0b77e-3ef2-11e5-8852-65a1554061bc.png)

**Comment by RIanDeLaCruz** [comment]
See commit related to this. Closing

**Comment by RIanDeLaCruz** [comment]
Kindly close when you've seen it fixed. Please see commit log about this issue

**Comment by janbelmonte** [comment]
@RIanDeLaCruz how did you fix this one?

**Comment by tekamoment** [comment]
@RIanDeLaCruz  seconded. I know it's about the ñ, but curious as to how it was fixed (and what caused the problem in the first place).

**Comment by RIanDeLaCruz** [comment]
content://media/external/file/79012

I've changed this part of the query. So, instead of the ñ appearing in the query for Benny, the nice name is used, which, I think, is similar to the slug

**Comment by RIanDeLaCruz** [comment]
Uhm, kindly see na the commit. The code change is there. I'm on mobile na lang.

**Comment by RIanDeLaCruz** [comment]
![screenshot_2015-08-11-22-45-17](https://cloud.githubusercontent.com/assets/7766185/9200574/0d1cf80e-407b-11e5-8a8f-d6b979b3fa74.png)
Here.

**Comment by janbelmonte** [comment]
Oh okay, got it. Nicely done.
