### ISSUE TITLE
Change end of search copy

### ISSUE THREAD

**Issue by tekamoment** [theguidon/theguidon-twentyfifteen#63]
"Sorry, we can't find anything with those keywords." shows up at the end of author searches. 
<img width="899" alt="screen shot 2015-08-10 at 12 34 30 am" src="https://cloud.githubusercontent.com/assets/765270/9155817/aaade36a-3ef7-11e5-84e8-97a968f9a9f2.png">
We could probably go with something friendlier?

**Comment by janbelmonte** [comment]
@RIanDeLaCruz this message should only be shown if there are 0 search results. If there are a few search results, there shouldn't be any message under. Please remove it from the end of author profile pages also.

@tekamoment Can you suggest different copy for this one? It should only be for when there are no search results at all.

**Comment by RIanDeLaCruz** [comment]
@janbelmonte I'll edit the plugin.

**Comment by tekamoment** [comment]
"This author has not written any articles yet."
^?

**Comment by janbelmonte** [comment]
@tekamoment If the author hasn't written anything yet then he/she wouldn't have a page, therefore 404. So no message. I think we can only put such a message on search results for keywords. Unless you tried to search for a name on the search bar? And there weren't any articles that mentioned that name? Cause I don't think we have a way to determine names from regular words if we want the search bar to show that message.

**Comment by RIanDeLaCruz** [comment]
@tekamoment @janbelmonte What's the final verdict on this, until further notice?

**Comment by janbelmonte** [comment]
@RIanDeLaCruz For now, just make sue the message doesn't appear in pages other than a 0 results page. If you've applied a fix for this already, tell me and I'll close the comment after testing

**Comment by RIanDeLaCruz** [comment]
I think I've done this one already
