### ISSUE TITLE
Banner title is not clickable

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#66]

**Comment by RIanDeLaCruz** [comment]
I'm finding this weird. According to the stacking order, it should be clickable. 

![2015-08-11-054347_1366x768_scrot](https://cloud.githubusercontent.com/assets/7766185/9185115/0c5e5c12-3fec-11e5-99b5-4351fe2d6734.png)

**Comment by janbelmonte** [comment]
Wow, sa Firefox dev tools ba to haha. Looks like it is...that's so weird

**Comment by RIanDeLaCruz** [comment]
Yup! Firefox Dev Tools. Don't remember if this is available in Chrome 

What's weird?

**Comment by janbelmonte** [comment]
Weird that it's properly stacked but behavior is wrong

**Comment by RIanDeLaCruz** [comment]
I'll just look it up. Last time I checked, the margin is the only part that's clickable. Try to find it by extending the anchor tag nested in the h1 to full width

**Comment by janbelmonte** [comment]
@RIanDeLaCruz all links except banner link are working for me

**Comment by RIanDeLaCruz** [comment]
Yun lang naman talaga ang hindi gumagana

**Comment by janbelmonte** [comment]
but but what did you mean by this
![screenshot 2015-08-11 22 36 23](https://cloud.githubusercontent.com/assets/9819894/9200234/7c350896-4079-11e5-83eb-b45f23344eae.png)

**Comment by RIanDeLaCruz** [comment]
That was just to be the link. Without the s

**Comment by janbelmonte** [comment]
Oh okay haha

**Comment by RIanDeLaCruz** [comment]
What are we going to do with this @janbelmonte

**Comment by janbelmonte** [comment]
@RIanDeLaCruz Didn't this only happen after you tried to make the whole image clickable? Try removing the div that you added muna and let's leave the title as link?

**Comment by RIanDeLaCruz** [comment]
It's always been like this. I've already removed everything I added to it.

**Comment by janbelmonte** [comment]
UY ano ka. Gumagana yan dati ah. HAHA

**Comment by janbelmonte** [comment]
I'll look through the styles na rin to see what's going on T_T

**Comment by RIanDeLaCruz** [comment]
Hindi nga siya gumagana sa prototype eh.

**Comment by janbelmonte** [comment]
pakyu!!!

HAHAJK sorry, i'll check it out
#professional
