### ISSUE TITLE
Add share buttons

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#67]
Please add it in between the byline/date and the feature-image
- for article-fullscreen, put it in between the section-label and the top of the content

Criteria for share buttons
- should have at least Facebook, Twitter, Email
- should show number of shares
- should be customizable (css)

Assign me to this issue once it's my turn to style.

**Comment by RIanDeLaCruz** [comment]
Isn't share buttons provided by a plugin or integration with the platforms?

**Comment by RIanDeLaCruz** [comment]
You are looking for a CSS Customizable share button, @janbelmonte ? Share buttons use images

**Comment by RIanDeLaCruz** [comment]
FB Share requires a FB Developer Account. It'd be better if this account was a GUIDON one.

Twitter can be used from the plugin, or encoded into the template

**Comment by RIanDeLaCruz** [comment]
http://stackoverflow.com/questions/22037021/custom-facebook-share-button
http://wordpress.stackexchange.com/questions/152097/facebook-share-functionality-in-wordpress-loop

Posting just for FB Reference

**Comment by RIanDeLaCruz** [comment]
https://dev.twitter.com/web/tweet-button (For custom Tweet button)

**Comment by RIanDeLaCruz** [comment]
http://stackoverflow.com/questions/22037021/custom-facebook-share-button

**Comment by RIanDeLaCruz** [comment]
http://wordpress.stackexchange.com/questions/152097/facebook-share-functionality-in-wordpress-loop

**Comment by janbelmonte** [comment]
@RIanDeLaCruz yup, i was hoping we could get rid of the image and create our own button out of css

**Comment by RIanDeLaCruz** [comment]
I've found a plugin that can supposedly do it.

**Comment by janbelmonte** [comment]
@RIanDeLaCruz alright, just @ me once you've applied it

**Comment by RIanDeLaCruz** [comment]
But it's not css. We could just change the images.

**Comment by janbelmonte** [comment]
@RIanDeLaCruz that's ayt

**Comment by RIanDeLaCruz** [comment]
Ok.

**Comment by RIanDeLaCruz** [comment]
I've added this plugin @janbelmonte 

https://wordpress.org/plugins/simple-share-buttons-adder/

You can edit styles and images.

**Comment by RIanDeLaCruz** [comment]
You could completely disable the given css and use your own.

**Comment by janbelmonte** [comment]
@RIanDeLaCruz has this been implemented on DEV?

**Comment by RIanDeLaCruz** [comment]
Yes it is implemented

**Comment by janbelmonte** [comment]
Okay, I'll style.
