### ISSUE TITLE
Add Multimedia section to homepage

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#69]

**Comment by RIanDeLaCruz** [comment]
I keep on forgetting this. I've already looked at some ways on how to do it. 

Question though. Will this be a pulling of videos from the account itself or will it be posts that have videos in them

**Comment by janbelmonte** [comment]
It can be either. Here are our options in order of idealism:
1. Use a plugin to pull latest 8 (? check prototype) videos directly from The GUIDON YouTube account and just display links/embed
2. Display links to all latest article pages that have video embeds (which we already have, but very few. we can just publish old videos in their own pages and use the original date)
3. Create 8 fields where SM can input URLs to videos that will be linked/displayed on homepage

**Comment by RIanDeLaCruz** [comment]
Noted

**Comment by RIanDeLaCruz** [comment]
So far, I've added 10. I've also added the generated class of each to the main-new.css file.

Just a little more styling on my side.

If you like, you could just see the changes.

**Comment by RIanDeLaCruz** [comment]
Used this: https://wordpress.org/plugins/youtube-channel/

**Comment by janbelmonte** [comment]
So this populates on its own na 'no?

On Wed, Aug 12, 2015 at 4:59 PM, Ian De La Cruz <notifications@github.com>
wrote:

> Used this: https://wordpress.org/plugins/youtube-channel/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theguidon/theguidon-twentyfifteen/issues/69#issuecomment-130222036>
> .
>



-- 
*Jan-Daniel S. Belmonte*
Graphic Designer
Quality Assurance Analyst, Rappler

(+63) 917 860 5870
www.janbelmonte.com

**Comment by RIanDeLaCruz** [comment]
Yup

**Comment by RIanDeLaCruz** [comment]
@janbelmonte There is a style issue with the multimedia box.

Also, what happens when someone clicks see all

**Comment by janbelmonte** [comment]
@RIanDeLaCruz what style issue? can you make an issue for it haha

When view all is clicked, _blank to The GUIDON channel page

**Comment by RIanDeLaCruz** [comment]
![image](https://cloud.githubusercontent.com/assets/7766185/9240491/9557e3b8-4199-11e5-90b1-e6a011e853f5.png)

The multimedia scrollbar is hidden under the footer

**Comment by janbelmonte** [comment]
Hmm that's not what I was trying to do though. Sige ganyan na lang muna.

**Comment by janbelmonte** [comment]
Got it, will fix later.

**Comment by RIanDeLaCruz** [comment]
ok
