### ISSUE TITLE
Remove SSBA comment, or remove <p> tags so that it doesn't push share buttons down

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#73]
<p class="copy">
     
</p>

![screenshot 2015-08-12 23 08 26](https://cloud.githubusercontent.com/assets/9819894/9227630/2a00219a-4147-11e5-9feb-c0897ebf4c69.png)

**Comment by RIanDeLaCruz** [comment]
@janbelmonte this happened after your style or before?

**Comment by janbelmonte** [comment]
I don't think my styles could've created a new paragraph, haha. It's before pa.

**Comment by RIanDeLaCruz** [comment]
I mean the pushing down thing. Gumagana siya sa akin eh. @janbelmonte

**Comment by RIanDeLaCruz** [comment]
Didn't need to remove the copy. Just edited the necessary style @janbelmonte 

Kindly check it now. Thanks.

**Comment by janbelmonte** [comment]
Hmm that's not what I was trying to do though. Sige ganyan na lang muna.
