### ISSUE TITLE
Share buttons on articles are too big

### ISSUE THREAD

**Issue by tekamoment** [theguidon/theguidon-twentyfifteen#76]
Self-explanatory.

<img width="721" alt="screen shot 2015-08-15 at 2 12 44 pm" src="https://cloud.githubusercontent.com/assets/765270/9287738/f1c67dac-4357-11e5-82ea-9bf47c6b62fe.png">

**Comment by RIanDeLaCruz** [comment]
This is desktop, yes?

**Comment by tekamoment** [comment]
@RIanDeLaCruz Yes, desktop.

**Comment by RIanDeLaCruz** [comment]
Fixed. It was just a setting in the plugin.

The size was caused by the disabling of the default styles.
