### ISSUE TITLE
Make pullout title box more transparent

### ISSUE THREAD

**Issue by RIanDeLaCruz** [theguidon/theguidon-twentyfifteen#80]
An issue raised by Alexis is that certain photos have their focus in the center of the image. By having an opaque title box, the image will not be seen

![2015-08-18-210806_1366x768_scrot](https://cloud.githubusercontent.com/assets/7766185/9330651/4ff3dba8-45ed-11e5-97e8-ce57e63fe9fb.png)

**Comment by RIanDeLaCruz** [comment]
I've already asked if putting a full image filter could work, Alexis was not into that idea. Having a less opaque image would work better,in her opinion

**Comment by janbelmonte** [comment]
For this, actually i'll be adding position classes for the center-title so
you can move it around per article. No need to change opacity cause it
looks tacky.

On Tuesday, August 18, 2015, Ian De La Cruz <notifications@github.com>
wrote:

> I've already asked if putting a full image filter could work, Alexis was
> not into that idea. Having a less opaque image would work better,in her
> opinion
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theguidon/theguidon-twentyfifteen/issues/80#issuecomment-132189088>
> .
>


-- 
Sent from Mobile

Jan-Daniel S. Belmonte
Graphic Designer

(+63) 917 860 5870
www.janbelmonte.com

**Comment by RIanDeLaCruz** [comment]
One question about that, though. 

How do you propose that we change position? Extra fields?

**Comment by janbelmonte** [comment]
Related to what I said previously, we'll be using a custom css plugin for
all pages, so they can just customize the center-title class for each
article. We'll list down the options in the technical documentation for
styles and templates.

On Wednesday, August 19, 2015, Ian De La Cruz <notifications@github.com>
wrote:

> One question about that, though.
>
> How do you propose that we change position? Extra fields?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theguidon/theguidon-twentyfifteen/issues/80#issuecomment-132413361>
> .
>


-- 
Sent from Mobile

Jan-Daniel S. Belmonte
Graphic Designer

(+63) 917 860 5870
www.janbelmonte.com

**Comment by RIanDeLaCruz** [comment]
You've found a plug-in or we're gonna make one?

**Comment by janbelmonte** [comment]
I have one that I used for my client project.

On Wednesday, August 19, 2015, Ian De La Cruz <notifications@github.com>
wrote:

> You've found a plug-in or we're gonna make one?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theguidon/theguidon-twentyfifteen/issues/80#issuecomment-132469203>
> .
>


-- 
Sent from Mobile

Jan-Daniel S. Belmonte
Graphic Designer

(+63) 917 860 5870
www.janbelmonte.com

**Comment by RIanDeLaCruz** [comment]
Ok. That's great!

**Comment by janbelmonte** [comment]
@RIanDeLaCruz my final decision for this is to move the title and content-meta to the content area, the same as in regular NSO articles. Realized that it will really block a lot of the images' focal points and that putting custom css on all pages would be tedious for your staff. Kindly take care of this. Thanks!

**Comment by janbelmonte** [comment]
I'll try to work on this myself for the meantime to lessen your load
