### ISSUE TITLE
"Next story" button

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#82]
Options:
- Next story is latest of same section
- Next story is latest of The GUIDON

**Comment by RIanDeLaCruz** [comment]
I can make this post newer than the current post. Is this acceptable?

**Comment by janbelmonte** [comment]
@RIanDeLaCruz yes, sure

**Comment by RIanDeLaCruz** [comment]
What do you think of showing the title of the next article?
