### ISSUE TITLE
Logo jumps down on small screens. 

### ISSUE THREAD

**Issue by RIanDeLaCruz** [theguidon/theguidon-twentyfifteen#86]
Logo goes down on screen width < 210

**Comment by janbelmonte** [comment]
Yuck who reported this?

On Wednesday, August 26, 2015, Ian De La Cruz <notifications@github.com>
wrote:

> Logo goes down on screen width < 210
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theguidon/theguidon-twentyfifteen/issues/86>.
>


-- 
Sent from Mobile

Jan-Daniel S. Belmonte
Graphic Designer

(+63) 917 860 5870
www.janbelmonte.com

**Comment by RIanDeLaCruz** [comment]
My friend. Tried it on a smaller phone.

**Comment by RIanDeLaCruz** [comment]
![image](https://cloud.githubusercontent.com/assets/7766185/9490483/cab67714-4c1a-11e5-8e56-e27bb01f1909.png)

**Comment by RIanDeLaCruz** [comment]
content://media/external/file/86910

**Comment by janbelmonte** [comment]
Got it. I'll fix.

On Wednesday, August 26, 2015, Ian De La Cruz <notifications@github.com>
wrote:

> content://media/external/file/86910
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theguidon/theguidon-twentyfifteen/issues/86#issuecomment-134929511>
> .
>


-- 
Sent from Mobile

Jan-Daniel S. Belmonte
Graphic Designer

(+63) 917 860 5870
www.janbelmonte.com

**Comment by RIanDeLaCruz** [comment]
![20150826_165904](https://cloud.githubusercontent.com/assets/7766185/9490561/2d1d2628-4c1b-11e5-89e6-d327008fc0e6.jpg)

**Comment by RIanDeLaCruz** [comment]
@janbelmonte another issue is  the spacing in the blurbs on mobile.

**Comment by janbelmonte** [comment]
Ok just create new issues as necessary

On Wednesday, August 26, 2015, Ian De La Cruz <notifications@github.com>
wrote:

> @janbelmonte <https://github.com/janbelmonte> another issue is the
> spacing in the blurbs on mobile.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theguidon/theguidon-twentyfifteen/issues/86#issuecomment-134929762>
> .
>


-- 
Sent from Mobile

Jan-Daniel S. Belmonte
Graphic Designer

(+63) 917 860 5870
www.janbelmonte.com

**Comment by RIanDeLaCruz** [comment]
But I'll fix that one na lang pala. 

It's just a small change. I'll fix it na lang
