### ISSUE TITLE
Banner title is difficult to read after the banner image is centered properly

### ISSUE THREAD

**Issue by RIanDeLaCruz** [theguidon/theguidon-twentyfifteen#88]
The image, before adding 'background-position: center', was not centered. Only the left side was showing.

I added the new style inline. Now, this happened.

![image](https://cloud.githubusercontent.com/assets/7766185/9491368/fe4f5eaa-4c20-11e5-9c42-ec2ae33245f7.png)

Permission to make the the gradient a full-gradient to make it readable.

**Comment by RIanDeLaCruz** [comment]
@janbelmonte

**Comment by RIanDeLaCruz** [comment]
@janbelmonte I'll just make it a full gradient

**Comment by janbelmonte** [comment]
@RIanDeLaCruz full gradient for mobile or for all?

**Comment by RIanDeLaCruz** [comment]
for banner lang

**Comment by janbelmonte** [comment]
@RIanDeLaCruz go ahead
