### ISSUE TITLE
Beyond Loyola pushes View All on medium screens

### ISSUE THREAD

**Issue by RIanDeLaCruz** [theguidon/theguidon-twentyfifteen#92]
![screen shot 2015-08-29 at 11 06 18](https://cloud.githubusercontent.com/assets/7766185/9560281/155c7370-4e3e-11e5-9cc2-8b4b80f5b48d.png)

**Comment by janbelmonte** [comment]
emotions: BV!!!!
logic: "finding a fix now. thanks for this"

**Comment by janbelmonte** [comment]
@RIanDeLaCruz did you use an iPad for this? our media queries detect device-width not screen-width

**Comment by RIanDeLaCruz** [comment]
Not an iPad

**Comment by janbelmonte** [comment]
@tekamoment can you check this out on an iPad please? :)

**Comment by RIanDeLaCruz** [comment]
Yep. This exists on my mini
