### ISSUE TITLE
Guest author page <title> does not match with guest author name

### ISSUE THREAD

**Issue by janbelmonte** [theguidon/theguidon-twentyfifteen#93]
![screen shot 2015-08-29 at 11 06 33 am](https://cloud.githubusercontent.com/assets/9819894/9560283/2a8ea326-4e3e-11e5-8627-11d8067cf812.png)

**Comment by RIanDeLaCruz** [comment]
Fixed this one already. Will be uploading to the main site already. Please see Dev site for the latest builds

**Comment by RIanDeLaCruz** [comment]
This is also a duplicate of #89

**Comment by janbelmonte** [comment]
Woops, closing this. Thanks @RIanDeLaCruz
