### ISSUE TITLE
Home page breaks layout at different browser widths

### ISSUE THREAD

**Issue by tekamoment** [theguidon/theguidon-twentyfifteen#96]
This problem returneth.

<img width="881" alt="screen shot 2015-08-29 at 10 06 57 pm" src="https://cloud.githubusercontent.com/assets/765270/9562265/603fb5bc-4e9a-11e5-9aa2-f6d1c3e7c294.png">
<img width="1009" alt="screen shot 2015-08-29 at 10 06 45 pm" src="https://cloud.githubusercontent.com/assets/765270/9562262/5f97d680-4e9a-11e5-980a-7e9c4d6aa68b.png">
<img width="1223" alt="screen shot 2015-08-29 at 10 06 41 pm" src="https://cloud.githubusercontent.com/assets/765270/9562263/603d0042-4e9a-11e5-8108-2e49451f3514.png">
<img width="1792" alt="screen shot 2015-08-29 at 10 06 35 pm" src="https://cloud.githubusercontent.com/assets/765270/9562264/603f6f62-4e9a-11e5-9ca5-c019f636ead4.png">

**Comment by janbelmonte** [comment]
Fixed on desktop.
- Ian to add specific char limit to headlines (40 chars).

**Comment by RIanDeLaCruz** [comment]
question about this.

When will the character limit be implemented? Or is it for all
